/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\themes\app\appTheme.ts
 * Command: astryx theme build src\themes\app\appTheme.ts
 * CLI: @astryxdesign/cli@0.6.5
 * Core: @astryxdesign/core@0.6.5
 */

/// <reference path="./app.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const appTheme: DefinedTheme;
