/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\themes\app\appTheme.ts
 * Command: astryx theme build src\themes\app\appTheme.ts
 * CLI: @astryxdesign/cli@0.6.5
 * Core: @astryxdesign/core@0.6.5
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
